
server:
  port: 8080

logging:
  level:
    org:
      springboot:
            security: info
            info: info

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include:
      - dev
      - auth
  output:
    ansi:
      enabled: always