
server:
  port: 80

logging:
  level:
    org:
      springboot:
            security: info
            info: info

spring:
  profiles:
    include:
      - dev
      - auth
  output:
    ansi:
      enabled: always